In [1]:
import tensorflow as tf

In [6]:
# 1 <= n < 7 1 ~ 6 까지 구성된 10행 1열 짜리 matrix 생성 
x = tf.random_uniform([10, 1], minval = 1, maxval = 7, dtype = tf.int32)

In [7]:
sess = tf.Session()

In [8]:
sess.run(x)

array([[3],
       [1],
       [3],
       [5],
       [5],
       [1],
       [4],
       [5],
       [2],
       [5]])

In [36]:
c = tf.constant([[1], [2]]) # 2행 1열
d = tf.constant([[3], [4]])
r = tf.concat([c,d], axis = 1) # 행으로 결합 axis = 1 주면 열로 결합

In [37]:
sess.run(r)

array([[1, 3],
       [2, 4]])

주사위 2개를 10번 굴리기 시행했을때 
10 x 3 매트릭스 텐서 생성
1열과 2열은 주사위를 시행했을 때 값이고
3열은 두개열의 합으로 구성된다.

In [31]:
a = tf.random_uniform([10,1], minval = 1, maxval = 7, dtype = tf.int32)
b = tf.random_uniform([10,1], minval = 1, maxval = 7, dtype = tf.int32)
sum = tf.add(a,b)
dice = tf.concat([a,b,sum], axis = 1)
sess.run(dice)

array([[ 3,  2,  5],
       [ 3,  2,  5],
       [ 4,  2,  6],
       [ 2,  3,  5],
       [ 4,  6, 10],
       [ 4,  5,  9],
       [ 4,  5,  9],
       [ 4,  5,  9],
       [ 3,  4,  7],
       [ 3,  1,  4]])