In [1]:
import tensorflow as tf

In [25]:
a = tf.constant([[1,2,3], [4,5,6,]])
# b = tf.constant([10])
# b = tf.constant([10,11,12])
# b = tf.constant([[10,11]]) # broad casting x 1행 2열이라 안됨
b = tf.constant([[10], [11]]) # 2행 1열로 broad casting 가능

In [26]:
c = a + b # c = tf.add(a,b)

In [27]:
sess = tf.Session()

In [28]:
sess.run(c)

array([[11, 12, 13],
       [15, 16, 17]])

In [29]:
x = tf.constant([[1,2],[3,4]])
y = tf.constant([[5,6],[7,8]])

In [30]:
# 대부분의 다른연산 element wise (요소별 연산)
z = tf.matmul(x,y) #matrix multiply (이건 행렬의 곱셈 둘중의 하나라도 matrix가 아니면 연산 안됨)

In [31]:
y = tf.multiply(x,y) # 행렬 곱하기
sess.run(y)

array([[ 5, 12],
       [21, 32]])

In [32]:
sess.run(z)

array([[19, 22],
       [43, 50]])