In [1]:
import tensorflow as tf

In [6]:
x = tf.placeholder(dtype=tf.float32)
z = tf.placeholder(dtype=tf.float32)
y = x * 2 + z

In [3]:
sess = tf.Session()

In [8]:
sess.run(y, feed_dict={x:[1,2,3], z:[3,3,3]})

array([5., 7., 9.], dtype=float32)

In [4]:
sess.run(y, feed_dict={x:[1,2,3]})

array([2., 4., 6.], dtype=float32)

In [5]:
sess.run(y, feed_dict={x:[11,12,13]})

array([22., 24., 26.], dtype=float32)